name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:


env:
  aws_access_key_id : ${{secrets.AWS_ACCESS_KEY_ID}}
  aws_secret_access_key : ${{secrets.AWS_SECRET_ACCESS_KEY}}
  

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    


    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraformproviders

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform init
      run: |
        echo "aws access key : ${{env.aws_access_key_id}}" 
        echo "aws secret key : ${{env.aws_secret_access_key}}"
        terraform init -backend-config="access_key=${{env.aws_access_key_id}}" -backend-config="secret_key=${{env.aws_secret_access_key}}"


    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: |
        terraform plan -var="aws_secret=${{env.aws_secret_access_key}}" -var="aws_access_key=${{env.aws_access_key_id}}" 


      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      run: |
        terraform apply -auto-approve -var="aws_secret=${{env.aws_secret_access_key}}" -var="aws_access_key=${{env.aws_access_key_id}}" 


